version: '{build}'
image: Visual Studio 2015
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
environment:
  BUILD_NUMBER: $(APPVEYOR_BUILD_NUMBER)
build_script:
- cmd: build.cmd
nuget:
  disable_publish_on_pr: true
test: off
artifacts:
- path: artifacts/*/*.*
- path: tests/**/*TestResults.*
deploy: off
